### ISSUE TITLE
Feature request: support for skewed volumes and periodic repeats

### ISSUE THREAD

**Issue by mkhorton** [SuboptimalEng/volume-rendering#1]
Thank you for sharing this library!

I have only a little experience with Three.js, but come from a scientific community that could really benefit from better visualisation of charge densities from crystals.

A charge density is gridded volumetric data forming a parallelpiped volume (ie not necessarily a cube or cuboid). Along with the gridded data are the three lattice vectors that define the shape of the box and also the periodicity. Ideally, the charge density can be visualised with several repeats in x, y and z to really help see the “infinite” nature of the charge in crystal.

If this sounds interesting I would be happy to provided test data, eg a 256x256x256 uint with the corresponding vectors, and happy to help test.

Thanks again for sharing!

**Comment by SuboptimalEng** [comment]
Hey! Thanks for reaching out. 

Rendering charge densities from crystals sounds like an interesting problem, but I don't think I'd have the time to work on this project much further (which is why I open-sourced it).

I'm wondering if you've had the chance to check out [3D Slicer](https://www.slicer.org/). It's an open-source, multi-platform, desktop app that is used for all sorts of scientific research (and served as an inspiration for my project). It might already support some of the features you are asking for. And it's even got Python scripting (which I noticed you're familiar with on your GitHub). I feel like this is the tool you're looking for.

Have a good one!

**Comment by mkhorton** [comment]
No worries, thanks for the reply and the pointers!

I have not checked out 3D Slicer but I will take a look. VTK already has some really nice support, but it’d be great to see a solution within the Three.js ecosystem too, hence my interest here.
